package Atacama::Model::AtacamaWikiDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';


__PACKAGE__->config(
    schema_class => 'AtacamaWiki::Schema',
);

=head1 NAME

Atacama::Model::AtacamaWikiDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Atacama>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<AtacamaWiki::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

Atacama Developer

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
