package Atacama::Model::AtacamaDB;

# ABSTRACT: Model for the order database

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Atacama::Schema',
);

1; # Magic true value required at end of module

__END__

=head1 SYNOPSIS

See L<Atacama>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Atacama::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48
